### ISSUE TITLE
model$TbS$Sector==NA in USEEIO2.0

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#103]
Latest USEEIO2.0 model has 6 totals_by_sector obs. having Sector==NA, see [TbS$Sector==NA.xlsx](https://github.com/USEPA/useeior/files/6087009/TbS.Sector.NA.xlsx).

@bl-young @catherinebirney could you check on this?

**Comment by WesIngwersen** [comment]
@MoLi7  Did this [commit ](https://github.com/USEPA/useeior/commit/970b2b32fbfdb0523acd381e985fc121a528a275 )resolve that?

**Comment by catherinebirney** [comment]
@MoLi7 The FBS on Data Commons have not been updated in about a month, so I don't think any recent changes to flowsa would impact useeio2.0 results

**Comment by bl-young** [comment]
We did make changes to how the data are processed in useeior since we removed the connection in flowsa (which removed some code in flowbysector_collapsed). I think we attempted to replicate that, but you may remember htere was discussion around handling None/NA from python before it got to R, so perhaps that issue has resurfaced.

**Comment by bl-young** [comment]
There is NAICS 541710 in this dataset which expired after 2002. I seem to recall @catherinebirney fixing this. Perhaps the FBS just needs to be updated. https://github.com/USEPA/flowsa/issues/49#issuecomment-775138465

**Comment by catherinebirney** [comment]
@bl-young can you add the most recent version of the file to the SharePoint folder so Mo can test? And if it works I'll update Data Commons

**Comment by bl-young** [comment]
I'll add that this is being caught by [checkSatelliteFlowLoss ](https://github.com/USEPA/useeior/blob/v2-alpha/R/SatelliteFunctions.R#L262) but the loss is so small that it doesn't hit the tolerance.

**Comment by bl-young** [comment]
Are we comfortable dropping flows where sector = NA (without warning) after checking that the flow loss is minimal to avoid issues in the future? Probably [here](https://github.com/USEPA/useeior/blob/v2-alpha/R/LoadSatellites.R#L56rl)

**Comment by bl-young** [comment]
@MoLi7  see this [commit](https://github.com/USEPA/useeior/commit/69badcf15a48398811ec345d62a9ad1e33e9f776)

**Comment by bl-young** [comment]
Can this be closed? @MoLi7
