### ISSUE TITLE
Deal with NAs in USEEIO2.0 model$TbS$SectorName

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#104]
This is NOT a duplicate of https://github.com/USEPA/useeior/issues/103.

@jvendries found sectors "331314" "S00201" "S00101" "S00202" do not have corresponding SectorName in model$TbS.

My explanation is because USEEIO2.0 is a commodity-based model, these industry sectors are not in `model$SectorNames`, hence no names are available for them.

Keeping them in `model$TbS` and `model$CbS` should not interrupt USEEIO2.0 model build, as they will be removed when `model$B` is converted to flow-by-commodity format [here](https://github.com/USEPA/useeior/blob/03eb1e8235665f3c3dc51584893265e9b48c38de/R/BuildModel.R#L88). However, if we are concerned about users getting confused by the NAs, we probably should come up with a solution.

Looping @WesIngwersen @bl-young @catherinebirney in for discussion.

**Comment by WesIngwersen** [comment]
We DO need the industry names for any industry used in the model and same for commodities, even if its not used in the final product.

**Comment by MoLi7** [comment]
> We DO need the industry names for any industry used in the model and same for commodities, even if its not used in the final product.

@WesIngwersen yes, I agree that we need all industry names. Because they are assigned when FbS is mapped from NAICS to BEA ([here](https://github.com/USEPA/useeior/blob/03eb1e8235665f3c3dc51584893265e9b48c38de/R/SatelliteFunctions.R#L46)), and FbS is always by-industry, I propose we directly use `useeior::Detail_IndustryCodeName_2012.rda` instead of `model$SectorNames` to paste the names. This way we don't need to worry about whether a model is commodity-based or industry-based.

**Comment by jvendries** [comment]
@MoLi7 If I understand correctly, this proposed change would not include the sector names for the disaggregated industries, as by this point in the code flow `model$SectorNames` has been disaggregated whereas `useeior::Detail_IndustryCodeName_2012.rda` is not modified during disaggregation. Is this correct?

An alternative solution could be to add a `model$IndustryNames` to the model, but the addition of another object similar (but not identical) to the already present `model$Industries` could be confusing.

**Comment by MoLi7** [comment]
@jvendries thanks for the reminder about disaggregation - it is a good point for not using `useeior::Detail_IndustryCodeName_2012.rda`.

@WesIngwersen and I briefly discussed about the alternative solution you brought up, he thinks we could have two `df`: `model$IndustryCodeName` and `model$CommodityCodeName` where there are a code (with location) column and a name column, ultimately they can replace `model$Industries`, `model$Commodities`, and `model$SectorNames`.

I was a bit hesitant on replacing `model$Industries`, `model$Commodities`, i.e. `string`, with `df`, because it will be less convenient to call them and require many modifications in the scripts. But I agree having both `model$Industries` and `model$IndusteyCodeName` can be confusing and redundant.

We have been constantly making changes to improve model objects organization, and I believe it will continue to be a challenge down the road. So please feel free share your thoughts as they will help us find solutions along the way.

**Comment by WesIngwersen** [comment]
My recommendation was more in the form of model$Commodities and model$Industries (keeping them) but making them either a list of df so then you could access model$Commodities$Code, model$Commodities$Name,model$Commodities$Location, and then for convenience a model$Commodities$Code_Loc for the standard "562111/US"

**Comment by jvendries** [comment]
@MoLi7 @WesIngwersen I think Wes' solution is good solution from a disaggregation perspective, since those dataframes could be modified to include the new sectors in a manner analogous to how the current industry and commodity string vectors are modified. However, this solution will require quite a bit of effort elsewhere since as you point out, it will require changes to the various scripts to accommodate the new objects. Depending on the amount of effort and the timeframe for V2.0, it could make sense to add a new object to deal with this issue specifically for a faster turn around. Either way I can modify the disaggregation functions to work with the changes to the objects.

**Comment by MoLi7** [comment]
Okay, let's try @WesIngwersen's recommendation and convert `model$Commodities` and `model$Industries` into `df`. I will create a Jira task and assign it to myself. @jvendries if you don't mind I will create and assign to you a related task to modify disaggregation functions.

**Comment by jvendries** [comment]
@MoLi7 Sounds good.

**Comment by MoLi7** [comment]
This issue is resolved by PR #106 .
