### ISSUE TITLE
Error with writeModelforAPI function

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeior#124]
I tried to use the function `writeModelforAPI`, (from the `master ` branch), and I am getting the following error when it tries to create the demand vectors : 
```
> # Write model for API
> useeior::writeModelforAPI(model,modeloutdir)
2021-04-23 10:51:57 INFO::Model matrices for API written to C:\Users\Nutzer\Documents\git\useeior\examples/build/data/USEEIOv2.0.
2021-04-23 10:51:57 INFO::Model demand vectors for API written to C:\Users\Nutzer\Documents\git\useeior\examples/build/data/USEEIOv2.0/demands.
Error in checkNamesandOrdering(flows$ID, rownames(model$B), "flows in flows.csv and rows in B matrix") : 
  flows in flows.csv and rows in B matrix not the same or not in the same order.
```
Is it because of this [issue](https://github.com/USEPA/useeior/issues/107), or simply because is it still under development?

Thank you

**Comment by WesIngwersen** [comment]
We recently converted 1 flow into 3 separate flows. I suspect it is related to this. I will look into it.

FYI @MoLi7

**Comment by WesIngwersen** [comment]
There is a case difference in model$SatelliteTable$flows  and model$B rownames that will need to be addressed

**Comment by MoLi7** [comment]
Yes, there is a similar case difference in indicators and rownames(B) [here](https://github.com/USEPA/useeior/blob/609a43e799d6571e206f2dfbea166de8ecb759da/R/BuildModel.R#L173). The solution is applying `tolower(factors$Flow)` to match B rownames.

I think it can be adopted to solve [this issue](https://github.com/USEPA/useeior/blob/609a43e799d6571e206f2dfbea166de8ecb759da/R/WriteModel.R#L198), too.
`checkNamesandOrdering(tolower(flows$ID), rownames(model$B), "flows in flows.csv and rows in B matrix")`

Or `flows$ID` can be set to lower case in the beginning to bypass this, if that's what we want.

**Comment by WesIngwersen** [comment]
Actually we don't ideally want to lower - why don't we just leave everything untransformed? That's how we decided to treat it with sectors

**Comment by WesIngwersen** [comment]
I started branch `remove_lower_transform` where i am testing removal of all tolower() instances in the package

**Comment by WesIngwersen** [comment]
`writeModelforAPI()` is now working without error in the new branch

**Comment by TheTisiboth** [comment]
Hello Wes
Thank you for your quick answers. Sadly, as I am testing it right now, I get the exact same error, despite your bug fix. Maybe something is wrong with my local setup ? I even tried to uninstall and reinstall the useeior package RStudio (but I don't think it is related with this issue).
I have tested the branch `remove_lower_transform`, with the following script : 

```
library(useeior)

model <- buildModel("USEEIOv2.0")

result <- calculateEEIOModel(model, perspective = "DIRECT", demand = "Production")

modeloutdir="C:\\Users\\Nutzer\\Documents\\git\\useeior\\examples"

useeior::writeModelforAPI(model,modeloutdir)
```

**Comment by WesIngwersen** [comment]
@TheTisiboth, did you rebuild useeior after pulling that branch.? Otherwise it will load the existing build version of useeior. Or an alternative to attaching the library is simply

```
library(devtools)
load_all()
```

That will load all the functions in that pulled version.

**Comment by TheTisiboth** [comment]
Oh ok that was my issue, sorry, it is working  without any error now.
Thanks a lot!
