### ISSUE TITLE
error with writeSectorCrosswalkforAPI

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeior#128]
Hello
I wanted to use this function, but I am getting the following error:

```
> useeior::writeSectorCrosswalkforAPI(model,modeloutdir)
2021-04-27 09:39:34 INFO::Sector crosswalk written to C:\Users\Nutzer\Documents\git\useeior\examples/build/data.
Error in exists(what, where, inherits = FALSE) : 
  first argument incorrect
```

I tried it on the branch `remove_lower_transform`
Is this a well-known error?
Thank you!

**Comment by MoLi7** [comment]
@TheTisiboth the function should be working fine, I suspect the error is caused by mixed use of `/` and `\` in your file path. Could you try to define `modeloutdir` and use `/`?

**Comment by TheTisiboth** [comment]
Oh you are right, it was as simple as that... Sorry!
