### ISSUE TITLE
Model$U and model$U_d not properly indexed

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#134]
rownames are missing

**Comment by MoLi7** [comment]
That's odd. I don't see mis-indexed model$U and model$U_d for any of these models: USEEIOv2.0s-GHG, USEEIOv2.0-GHG_nodisagg, and USEEIOv2.0i-GHG_nodisagg.

To confirm it, I added simple check code below right after model$U and model$U_d are [created](https://github.com/USEPA/useeior/blob/3d1bf212c3a840dfefa0aa2daa2a9577dce0567e/R/BuildModel.R#L43-L48). Could you test it at your end? @WesIngwersen 

> model$U <- as.matrix(dplyr::bind_rows(cbind(model$UseTransactions,
                                              FinalDemand_df),
                                        model$UseValueAdded)) # Use
  if (!identical(rownames(model$U), c(model$Commodities$Code_Loc,
                                     model$ValueAddedSectors$Code_Loc))) {
    stop("rownames of model$U are not correct!")
  }
  model$U_d <- as.matrix(dplyr::bind_rows(cbind(model$DomesticUseTransactions,
                                                DomesticFinalDemand_df),
                                          model$UseValueAdded)) # DomesticUse
  if (!identical(rownames(model$U_d), c(model$Commodities$Code_Loc,
                                       model$ValueAddedSectors$Code_Loc))) {
    stop("rownames of model$U_d are not correct!")
  }

**Comment by WesIngwersen** [comment]
```
>   model$U <- as.matrix(dplyr::bind_rows(cbind(model$UseTransactions,
+                                               FinalDemand_df),
+                                         model$UseValueAdded)) # Use
> rownames(model$U)
NULL
```

I'm suspecting it might be my version of dplyr, which is `0.8.3`. i will look up to see if they make some changes in `bind_rows()` to index rows in a more recent version

**Comment by WesIngwersen** [comment]
Yes that was the issue..it might have been the dplyr dependency vctrs package that was old..an update to the most recent version results in row names being applied in that transformation
