### ISSUE TITLE
writeModeltoXLSX doesn't overwrite old model metadata

### ISSUE THREAD

**Issue by bl-young** [USEPA/useeior#149]
I'm finding that changing a model configuration _after_ I've already written it to excel using writeModeltoXLSX can lead to issues where model components don't get accurately updated when using writeModeltoXLSX again.

In this case, updating the indicators, the matrices are updated fine in excel, but the metadata (e.g. indicators tab) do not get updated because the metadata from the old model are used.

This section here, I believe: https://github.com/USEPA/useeior/blob/master/R/WriteModel.R#L93-L97

**Comment by MoLi7** [comment]
`writeModeltoXLSX` is designed to 'write model to .xlsx' only, overwriting old model metadata should be handled by `writeModelMetadata`.

If model metadata is updated but `writeModelMetadata` is not re-run to overwrite the old files, we probably should consider removing the if-else in L93-L97 and forcing `writeModelMetadata` anyway.

**Comment by bl-young** [comment]
Agreed. I don't think its clear to a user that they would need to re-run `writeModelMetadata` before `writeModeltoXLSX`
