### ISSUE TITLE
Store national totals by model sector list

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#16]
Need to store national totals by sector for satellite table to have them externally available

**Comment by WesIngwersen** [comment]
Added sub list of sattablelist called 'totals_by_sector' which will be a list of national totals by sector that can be directly accessed [93a8018](https://github.com/USEPA/useeior/commit/d3d11385ecc2fd9e67f3b2a45638e760193a8018)

**Comment by MoLi7** [comment]
@WesIngwersen I further modified and renamed sattablelist and updated satellite components in model, see [https://github.com/USEPA/useeior/commit/952d120df5c0f2bd56a325b6575391b5d991a981](url)
