### ISSUE TITLE
Integrate model validation (and other documentation)

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#165]
I initially wanted to add `ModelValidation.Rmd` as a standard [`vignette`](https://r-pkgs.org/vignettes.html), but after some research I realized that, upon package building via `devtools::build()`, `vignette` will only generate html or pdf documents, which are not viable in terms of version control, nor are they easily readable on GitHub.

A workaround is to create a new `/inst/doc` folder, store the `ModelValidation.Rmd` in it, set `keep_md: yes` when knitting the `.Rmd`, then any changes in the validation process and results are version controlled in the `.md`. This can be applied to other documents that we want to keep close to core `useeior` code/data.

If we prefer not to include the these documents in the bundled package, we can add `/inst/doc` to `.Rbuildignore`.

@WesIngwersen please share your thoughts.

**Comment by WesIngwersen** [comment]
That's great info. I think we need to discuss mord. This will present the results of a given model, right? This is a quearion of how much individual model docs we want to keep in the package. As far as the package is concerned, each of the model specs are equal so do we provide a ModelValidation md/html that covers every model spec in the package?

**Comment by MoLi7** [comment]
> This will present the results of a given model, right?

Each model having a designated `ModelValidation.Rmd/.md` is redundant.

> so do we provide a ModelValidation md/html that covers every model spec in the package?

Yes, one `ModelValidation.Rmd/.md` for the most comprehensive model (e.g. USEEIOv2.0) which is also eligible for validating other models that have equal specs (e.g. USEEIOv2.0-GHG) is a good alternative.

Then for each major model update (2.0 -> 2.1), a designated `ModelValidation.Rmd/.md` is justifiable.

**Comment by WesIngwersen** [comment]
Please reconcile this plan with the validation being done with gh-actions in PR #180

**Comment by MoLi7** [comment]
Main part of this plan (validation) is implemented by proposal in PR https://github.com/USEPA/useeior/pull/168 and solution in PR https://github.com/USEPA/useeior/pull/180.
