### ISSUE TITLE
Consider revising production demand vector

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#178]
The current formula for production demand is
```
y_p <- y_dc + y_e + y_d_delta
```
https://github.com/USEPA/useeior/blob/a5ff886055cf6971446ba25121b66e4ea8aa66f3/R/DemandFunctions.R#L43

The _d in the first and third term on right show values derived from the final demand side of the Domestic Use table. The reason for this is to take out the imported goods from final consumption and from change in inventories.  However, this is still used with an direct requirements matrix from the full Use table which includes foreign requirements.  Thus it it not used in the validation for [output here ](https://github.com/USEPA/useeior/blob/a5ff886055cf6971446ba25121b66e4ea8aa66f3/R/ValidateModel.R#L67) or [for the E totals here](https://github.com/USEPA/useeior/blob/a5ff886055cf6971446ba25121b66e4ea8aa66f3/R/ValidateModel.R#L17)

This issue is to get feedback on a potential change to be posed in the comments.

**Comment by WesIngwersen** [comment]
My proposal is to change the production vector for the full model to just be the sum of all the final demand columns. Including imports will more than remove imports from consumption, it will also correct the model so that 
```
q = L*y_p  
```
the new y_p will thus be 
```
y_p <- y_c + y_e + y_delta + y_m
```
(where y_m) are imports, but they are negative such that it is equivalent to the commonly understood economic definition of GDP as 

```
GDP = C + I + G + (X - M)
```
where C=household spending, G = gov spending, I = investment, X = exports and M = imports

**Comment by WesIngwersen** [comment]
@MoLi7  @jvendries @bl-young  thoughts?

**Comment by MoLi7** [comment]
Yes, it makes sense to add import as a part of `y_p` for simplicity.

I suppose this does not conflict with the need for a domestic production demand vector that supports validation of domestic requirements matrix, right?
https://github.com/USEPA/useeior/blob/20013cf7bb449f25baf92b2ba6b58afb9f70fbcf/R/DemandFunctions.R#L57-L69

**Comment by WesIngwersen** [comment]
Correct it would not conflict nor obviate the need for a separate domestic production demand

**Comment by WesIngwersen** [comment]
I will start an issue_178 branch off of develop to draft changes
