### ISSUE TITLE
Improve aggregation functions related to satellite tables

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#18]
1 The aggregation calls need to be put into a common function. this function needs to be designed to handle multiple aggregation functions (like weighted mean and sum).  The base `aggregate` function from stats is not capable of doing this, but [dplyr and data.table packages have this capability](https://stackoverflow.com/questions/32561050/multiple-functions-in-aggregate). We need one with a convenient and easy to use weighted mean function. 

[1st](https://github.com/USEPA/useeior/blob/8d2cfa91ffd2189a35cbba9bc2754a90fa015029/R/SatelliteFunctions.R#L40
)
[2nd](https://github.com/USEPA/useeior/blob/8d2cfa91ffd2189a35cbba9bc2754a90fa015029/R/SatelliteFunctions.R#L131)
DQ values always need to be aggregated with a weighted mean and  the data values generally with sums.

**Comment by WesIngwersen** [comment]
@MoLi7 
Changed into a bug, because model building throws errors until
-other DQ columns are added to GHG excel and present in csv imports (see Jira 503)
-this first aggregation function is replaced with a function to handle all the data quality values.

**Comment by WesIngwersen** [comment]
@MoLi7 I understood this was resolved but I don't see the resolution in https://github.com/USEPA/useeior/blob/master/R/SatelliteFunctions.R#L141

**Comment by MoLi7** [comment]
The latest resolution to the aggregation function is actually https://github.com/USEPA/useeior/blob/7da0042b07ef20d6c6e1200d1a0d4d9530d57ae5/R/SatelliteFunctions.R#L135-L137. The function can be tested in https://github.com/USEPA/useeior/blob/master/tests/testthat/test-SatelliteFunctions.R
