### ISSUE TITLE
Document analytical and viz functions

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#182]
There should be some documentation of the analytical (like contribution analysis) or visualization functions in the README or wiki

**Comment by MoLi7** [comment]
Add small example(s) of validation, too.

**Comment by MoLi7** [comment]
Validation example added in https://github.com/USEPA/useeior/commit/61563fee87918e3b54468061146f1e12a8c3dc22.
Visualization example added in https://github.com/USEPA/useeior/commit/ab54243ab092dbf5362d48c1639e516508cfc96e.
Contribution analysis example added in https://github.com/USEPA/useeior/commit/3a77810a2c0e7bfe503d8aa3c24bf56e781a8d8a.

**Comment by MoLi7** [comment]
The built-in `USEEIOv2.0.1` model is used to demo validation, visualization and contribution analysis. Because the model has 400+ sectors, I chose not to include the point figure of `N` or `D` matrix results - it will be an extremely long figure thus not viewer friendly.
Feel free to add more or modify the existing examples. @WesIngwersen

**Comment by WesIngwersen** [comment]
No need to present all visualizations

**Comment by WesIngwersen** [comment]
There is no mention of any of the Rmd files in inst/doc.  Should we mention those somewhere to describe how they are used?

**Comment by MoLi7** [comment]
> There is no mention of any of the Rmd files in inst/doc. Should we mention those somewhere to describe how they are used?

Validation `Rmds` are described in dcea044752021025a2aa417f3a2313ac1915ffe5. Compare model `Rmds` are describe in b57de2e668715c4b0f44e67643221778834533f9. Example.Rmd is described in 31b36d7fe49a6382fe1543ec28f56aabe8dced93.
@WesIngwersen
