### ISSUE TITLE
Industry model failing domestic validation

### ISSUE THREAD

**Issue by bl-young** [USEPA/useeior#190]
```
model <- buildModel('USEEIOv2.0i-GHG_nodisagg')
dom_val <- compareEandLCIResult(model,use_domestic=TRUE, tolerance = 0.01)
```

```
Error in L %*% demand : requires numeric/complex matrix/vector arguments 
3. getScalingVector(model$L_d, y) at ValidateModel.R#56
2. calculateProductofLeontiefAndProductionDemand(model, use_domestic) at ValidateModel.R#33
1. compareEandLCIResult(model, use_domestic = TRUE, tolerance = 0.01) 
```

**Comment by WesIngwersen** [comment]
This would occur for one because the new mu is used in the domestic validation, but hasnt been transformed into industry format. 

@bl-young @MoLi7

**Comment by WesIngwersen** [comment]
Or Final Demand in both

Use and Import Matrix must have been  already transformed before creating mu

**Comment by MoLi7** [comment]
> This would occur for one because the new mu is used in the domestic validation, but hasnt been transformed into industry format.

@WesIngwersen actually `mu` is transformed to industry format.
https://github.com/USEPA/useeior/blob/aa39236b1eb62ee3686471c3a136b4c2dc1e64dd/R/LoadIOTables.R#L133

The root cause is because it is forced to a `data.frame` instead of a `numeric` vector and causing `DomesticProduction` demand vector to be a `df` then lead to validation failure.
https://github.com/USEPA/useeior/commit/6f29af5ec1a65cddd8a9bb6f9d61a11b6fd96cb0 should fix this.

**Comment by bl-young** [comment]
The error is resolved, but the validation for commodity output equals domestic use plus production demand is failing
https://github.com/USEPA/useeior/runs/4539468910?check_suite_focus=true#step:7:217

**Comment by MoLi7** [comment]
> The error is resolved, but the validation for commodity output equals domestic use plus production demand is failing https://github.com/USEPA/useeior/runs/4539468910?check_suite_focus=true#step:7:217

In the validation function, the calculation of `x` is a mix of by-commodity vector (before `+`) and by-industry vector (after `+`), which is incorrect.
https://github.com/USEPA/useeior/blob/6f29af5ec1a65cddd8a9bb6f9d61a11b6fd96cb0/R/ValidateModel.R#L104-L105

For an `industry` model, `compareCommodityOutputandDomesticUseplusProductionDemand` should still use `DomesticProduction` demand vector in by-commodity form to ensure the compared objects are correctly calculated. Reverting the demand vector back to by-commodity form might be a solution for industry models.

**Comment by WesIngwersen** [comment]
That function was written with a limited scope at the time for testing commodity models.  So industry models tests shouldn't use that one unless it was rescoped

**Comment by WesIngwersen** [comment]
Validation of output with Leontief and validation of environmental totals  if they run the domestic models as well as the complete models would be sufficient

**Comment by bl-young** [comment]
So it sounds like the solution is skipping that test for industry models?

https://github.com/USEPA/useeior/blob/17aa4ed103099231a45801d2f0ff710342f41b34/R/ValidateModel.R#L305-L309

**Comment by MoLi7** [comment]
> So it sounds like the solution is skipping that test for industry models?
> 
> https://github.com/USEPA/useeior/blob/17aa4ed103099231a45801d2f0ff710342f41b34/R/ValidateModel.R#L305-L309

I agree.

**Comment by bl-young** [comment]
resolved by https://github.com/USEPA/useeior/pull/191/commits/68c60bca53c843b37484016146ff0fc33e257d64
