### ISSUE TITLE
Update WAT and LAND file refs in >= v2.0.1 specs

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#193]
Adding this to track that this issue is addressed before minting v1  

fyi @MoLi7

**Comment by catherinebirney** [comment]
updated with this [commit](https://github.com/USEPA/useeior/commit/f64cf9625e5ed40be66793682cc8846a477381e3)

**Comment by WesIngwersen** [comment]
Thanks. Closing.
