### ISSUE TITLE
Define default demand vectors

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#195]
Somewhere in the documentation outside the function docstrings the default demand vectors need to be defined and linked to in the README or other places where they are described

**Comment by MoLi7** [comment]
Doc about default vectors are in [ModelSpecification.md](https://github.com/USEPA/useeior/blob/develop/format_specs/ModelSpecification.md#demand-vector-specifications) in `develop` branch. I added link to it in [README](0f4ae15cde86870c8b512db165b9d01ec20a7591).
