### ISSUE TITLE
calculateConsumptionContributiontoImpact does not calculate contribution percentage

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#197]
https://github.com/USEPA/useeior/blob/f2eaf5ea31fb45a3be15f062ee734e196a51691c/R/CalculationFunctions.R#L253-L260

The output of this function is not a matrix of 0-100% values like those of `calculateSectorContributiontoImpact` and `calculateFlowContributiontoImpact` in which `calculatePercentContributiontoImpact` is used to divide two vectors to get a contribution percentage.

Could you correct me if I'm misunderstanding it? If the intent is not to calculate percentages, would you consider renaming the function and not using `Contributionto` in the name? @bl-young

**Comment by bl-young** [comment]
This function creates a sector by sector matrix for a given impact from a given demand vector. So it is not percentages (but is 1 step away from being a percent, simply dividing a cell by sum of the matrix). If you want to rename it for consistency with the other functions, perhaps `calculateSectorbySectorImpact`?

**Comment by MoLi7** [comment]
Since it's a sector x sector matrix, I suppose it's important to clarify what's on the rows and columns like how you did it in the doc
https://github.com/USEPA/useeior/blob/f2eaf5ea31fb45a3be15f062ee734e196a51691c/R/CalculationFunctions.R#L251

So, maybe `calculateSectorPurchasedbySectorSourcedImpact`?

Plus, if there are negative demand for certain sectors in `y`, there will be negative values in `impacts` for those sectors - should they be interpreted as "reduced impact"?

**Comment by bl-young** [comment]
> So, maybe `calculateSectorPurchasedbySectorSourcedImpact`?

Sure that works for me.

> Plus, if there are negative demand for certain sectors in `y`, there will be negative values in `impacts` for those sectors - should they be interpreted as "reduced impact"?

Yes I believe that would be accurate.

**Comment by MoLi7** [comment]
Issue and discussion resolved by eb775cfb993828c7fc3ff470052d773863a58cde. Thanks @bl-young for clarification!

**Comment by WesIngwersen** [comment]
It would be good to clarify when these analysis functions based on marginal impacts and when they are based on the full model calculation. I don't know if this should be the names or just the way they are presented in documentation

**Comment by MoLi7** [comment]
In fact, `calculateFlowContributiontoImpact` is based on direct+indirect impacts using `M` or `M_d`, while `calculateSectorContributiontoImpact` and `calculateSectorPurchasedbySectorSourcedImpact`) are based on direct impacts using `D`.

**Comment by WesIngwersen** [comment]
@MoLi7, I understand the the confusion, because they are using the D matrix as an input into calculations. But the values in the D matrix get multiplied by a value that includes the total requirements, which is the L in the case of  calculateSectorContributiontoImpact, or Ly, in the case of calculateSectorPurchasedbySectorSourcedImpact, which makes them equivalent to N and LCIA, respectively, which are both matrices representing direct+indirect impacts.

**Comment by MoLi7** [comment]
Thanks for the clarification - it makes total sense now. I see that you want to use `calculateSectorContributiontoImpact`, so there has to be a multiplication of `L` and `D` instead of directing using `N`. This is fine with me as long as the docs are clear - I edited them in d5ab44f26d06abd92606fd9bbb9641fa94b13bf2.

In README, explanation about these contribution analyses are updated in e51d1f447d4672d888855532377fc2f1bff16d91.
