### ISSUE TITLE
URL update for census naics data

### ISSUE THREAD

**Issue by bl-young** [USEPA/useeior#198]
https://github.com/USEPA/useeior/blob/b9b6d0fe7189ab86caf9552a413386bad71c6b36/data-raw/MasterCrosswalk.R#L216

I believe the url has been updated see https://www.census.gov/naics/?68967

https://www.census.gov/naics/concordances/2012_to_2017_NAICS.xlsx

This may apply to more than just this line

**Comment by MoLi7** [comment]
Should be addressed by 2ff3ccac808f1c50ec909652962e1bded0f3cf0c.

**Comment by bl-young** [comment]
@MoLi7 the link looks the same still in that commit?

**Comment by MoLi7** [comment]
Opened PR https://github.com/USEPA/useeior/pull/201 to correct the link.
