### ISSUE TITLE
Invalid margin result for s00402/us

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#20]
Reported by Kevin Ummel
for  modelname <- "USEEIOv2.0-GHG"
price_adjusted_margin$U_margin_pur_2018[1,]

1111a0/us   1111b0/us   111200/us   111300/us   111400/us   111900/us   112120/us   1121a0/us   112300/us   112a00/us   113000/us
     0.1086      0.0732      0.1687      0.1401      0.0792      0.0652      0.0839      0.0788      0.0574      0.0597      0.1298
  114000/us   115000/us   211000/us   212100/us   212230/us   2122a0/us   212310/us   2123a0/us   213111/us   21311a/us   221100/us
     0.1455      0.0000      0.1253      0.1970      0.1132      0.0828      0.2001      0.1541      0.0000      0.0000      0.0000
  221200/us   221300/us   233210/us   233262/us   230301/us   230302/us   2332a0/us   233412/us   2334a0/us   233230/us   2332d0/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  233240/us   233411/us   2332c0/us   321100/us   321200/us   321910/us   3219a0/us   327100/us   327200/us   327310/us   327320/us
     0.0000      0.0000      0.0000      0.0511      0.0490      0.0591      0.0703      0.1911      0.1214      0.1172      0.1138
  327330/us   327390/us   327400/us   327910/us   327991/us   327992/us   327993/us   327999/us   331110/us   331200/us   331313/us
     0.1153      0.0690      0.1206      0.1199      0.1630      0.2572      0.0920      0.0877      0.0378      0.0471      0.0338
  33131b/us   331410/us   331420/us   331490/us   331510/us   331520/us   332114/us   33211a/us   332119/us   332200/us   332310/us
     0.0265      0.0432      0.0257      0.0246      0.0223      0.0221      0.0182      0.0157      0.0287      0.1562      0.0160
  332320/us   332410/us   332420/us   332430/us   332500/us   332600/us   332710/us   332720/us   332800/us   332913/us   33291a/us
     0.0312      0.0247      0.0110      0.0099      0.0789      0.0188      0.0090      0.0556      0.0215      0.2095      0.0405
  332991/us   332996/us   33299a/us   332999/us   333111/us   333112/us   333120/us   333130/us   333242/us   33329a/us   333314/us
     0.0763      0.0314      0.1604      0.0573      0.0542      0.2433      0.0325      0.0389      0.0319      0.0745      0.0708
  333316/us   333318/us   333414/us   333415/us   333413/us   333511/us   333514/us   333517/us   33351b/us   333611/us   333612/us
     0.3854      0.1410      0.0987      0.1213      0.0275      0.0582      0.0515      0.0600      0.0548      0.0626      0.0442
  333613/us   333618/us   333912/us   33391a/us   333920/us   333991/us   333993/us   333994/us   33399a/us   33399b/us   334111/us
     0.0401      0.0720      0.0294      0.0611      0.0532      0.1995      0.0385      0.0320      0.0328      0.0703      0.3058
  334112/us   334118/us   334210/us   334220/us   334290/us   334413/us   334418/us   33441a/us   334510/us   334511/us   334512/us
     0.0855      0.2596      0.2283      0.1012      0.0282      0.0673      0.0262      0.0309      0.0371      0.0126      0.0197
  334513/us   334514/us   334515/us   334516/us   334517/us   33451a/us   334300/us   334610/us   335110/us   335120/us   335210/us
     0.0158      0.0502      0.0618      0.0568      0.0281      0.0781      0.9358      0.0220      0.1569      0.3389      1.1184
  335221/us   335222/us   335224/us   335228/us   335311/us   335312/us   335313/us   335314/us   335911/us   335912/us   335920/us
     0.2937      0.1857      0.2573      0.1260      0.0704      0.1018      0.0369      0.0813      0.0889      0.2424      0.0394
  335930/us   335991/us   335999/us   336111/us   336112/us   336120/us   336211/us   336212/us   336213/us   336214/us   336310/us
     0.1017      0.0105      0.0534      0.2399      0.0378      0.0217      0.0531      0.0303      0.0533      0.0760      0.0321
  336320/us   336350/us   336360/us   336370/us   336390/us   3363a0/us   336411/us   336412/us   336413/us   336414/us   33641a/us
     0.1090      0.0664      0.0271      0.0288      0.0655      0.0500      0.0069      0.0134      0.0054      0.0095      0.0103
  336500/us   336611/us   336612/us   336991/us   336992/us   336999/us   337110/us   337121/us   337122/us   337127/us   33712n/us
     0.0335      0.0112      0.0919      0.0692      0.0103      0.0689      0.0945      0.2986      0.9466      0.3008      0.6500
  337215/us   33721a/us   337900/us   339112/us   339113/us   339114/us   339115/us   339116/us   339910/us   339920/us   339930/us
     0.2422      0.1277      0.4632      0.0747      0.1198      0.0642      0.2847      0.0471      0.2384      0.4663      3.5744
  339940/us   339950/us   339990/us   311111/us   311119/us   311210/us   311221/us   311225/us   311224/us   311230/us   311300/us
     0.2491      0.1340      0.2821      0.0972      0.0649      0.0574      0.0545      0.0389      0.0459      0.1260      0.0749
  311410/us   311420/us   311513/us   311514/us   31151a/us   311520/us   311615/us   31161a/us   311700/us   311810/us   3118a0/us
     0.0703      0.0769      0.0607      0.0771      0.0788      0.0518      0.0639      0.0650      0.0713      0.0627      0.0813
  311910/us   311920/us   311930/us   311940/us   311990/us   312110/us   312120/us   312130/us   312140/us   312200/us   313100/us
     0.0462      0.0448      0.0270      0.0483      0.0688      0.0624      0.1070      0.1939      0.1219      0.0963      0.0565
  313200/us   313300/us   314110/us   314120/us   314900/us   315000/us   316000/us   322110/us   322120/us   322130/us   322210/us
     0.0592      0.0308      0.2716      1.2248      0.2983      2.1550      1.2143      0.0868      0.1046      0.0665      0.0401
  322220/us   322230/us   322291/us   322299/us   323110/us   323120/us   324110/us   324121/us   324122/us   324190/us   325110/us
     0.0572      0.0496      0.1099      0.0470      0.0348      0.0457      0.0691      0.0255      0.0258      0.0847      0.0345
  325120/us   325130/us   325180/us   325190/us   325211/us   3252a0/us   325411/us   325412/us   325413/us   325414/us   325310/us
     0.1631      0.0811      0.1059      0.0401      0.0472      0.0171      0.0411      0.3111      0.0447      0.0960      0.0755
  325320/us   325510/us   325520/us   325610/us   325620/us   325910/us   3259a0/us   326110/us   326120/us   326130/us   326140/us
     0.0425      0.0497      0.0184      0.0608      0.1859      0.0183      0.0598      0.0229      0.0528      0.0160      0.0980
  326150/us   326160/us   326190/us   326210/us   326220/us   326290/us   423100/us   423400/us   423600/us   423800/us   423a00/us
     0.0462      0.0190      0.0316      0.1295      0.0726      0.0226      0.0000      0.0000      0.0000      0.0000      0.0000
  424200/us   424400/us   424700/us   424a00/us   425000/us   4200id/us   441000/us   445000/us   452000/us   444000/us   446000/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  447000/us   448000/us   454000/us   4b0000/us   481000/us   482000/us   483000/us   484000/us   485000/us   486000/us   48a000/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  492000/us   493000/us   511110/us   511120/us   511130/us   5111a0/us   511200/us   512100/us   512200/us   515100/us   515200/us
     0.0000      0.0000      0.0840      0.0573      0.0813      0.0594      0.0390      0.0056      0.0409      0.0000      0.0000
  517110/us   517210/us   517a00/us   518200/us   519130/us   5191a0/us   522a00/us   52a000/us   523900/us   523a00/us   524113/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  5241xx/us   524200/us   525000/us   531hso/us   531hst/us   531ore/us   532100/us   532400/us   532a00/us   533000/us   541100/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  541511/us   541512/us   54151a/us   541200/us   541300/us   541610/us   5416a0/us   541700/us   541800/us   541400/us   541920/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  541940/us   5419a0/us   550000/us   561300/us   561700/us   561100/us   561200/us   561400/us   561500/us   561600/us   561900/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  562000/us   611100/us   611a00/us   611b00/us   621100/us   621200/us   621300/us   621400/us   621500/us   621600/us   621900/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  622000/us   623a00/us   623b00/us   624100/us   624400/us   624a00/us   711100/us   711200/us   711500/us   711a00/us   712000/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  713100/us   713200/us   713900/us   721000/us   722110/us   722211/us   722a00/us   811100/us   811200/us   811300/us   811400/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  812100/us   812200/us   812300/us   812900/us   813100/us   813a00/us   813b00/us   814000/us   s00500/us   s00600/us   491000/us
     0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000      0.0000
  s00102/us    gslge/us    gslgh/us    gslgo/us   s00203/us   s00401/us   s00402/us   s00300/us   s00900/us
     0.0000      0.0000      0.0000      0.0000      0.0000      1.0259 -30970.3895      0.0000      0.0000

**Comment by MoLi7** [comment]
I believe this issue (S00402' U_pur_margin < 0) originated from [here](https://github.com/USEPA/useeior/blob/ba75e027b8c0b16802b58520f9de6a43fb546328/R/AddMarginImpacts.R#L15) where fractions of margin sectors (transportation, wholesale, retail) in producer price were calculated:
`MarginCoefficients <- as.matrix(Margins[, c("Transportation", "Wholesale", "Retail")]/Margins[, c("ProducersValue")])`

Because in the original BEA intermediate margin table, S00402's producer values add up == -1, the calculations above cause the MarginCoefficients of transportation, wholesale, retail all being negative value. These negative values are later used to derive [A_margin](https://github.com/USEPA/useeior/blob/ba75e027b8c0b16802b58520f9de6a43fb546328/R/AddMarginImpacts.R#L31-L39) and eventually cause S00402's margin in purchaser's value become negative.

I'm thinking a possible solution could be forcing all MarginCoefficients to >=0 as the following, since they are only used for allocation purposes.
`MarginCoefficients <- abs(as.matrix(Margins[, c("Transportation", "Wholesale", "Retail")]/Margins[, c("ProducersValue")]))`

@WesIngwersen what do you think?

**Comment by WesIngwersen** [comment]
Yes, I don't know any good way around that at this point without understanding the data a little more.  So your suggestion is the only solution I can think of to avoid the bug. We just need to document somewhere what we did. thanks
