### ISSUE TITLE
Initializing Disaggregation of IO tables is extremely slow for industry model (USEEIOv2.0-i-411)

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#210]
A user reached out with a question about industry models:
> I notice as I switch a model (the 411 industry/commodity one, v2.0) from commodity to industry that it is “iterating” for a while after the “Initializing disaggregation of IO tables”.  Does that sounds right?

I tried it at my end and can confirm it is indeed quite slow.

https://user-images.githubusercontent.com/28787399/153088042-6a39b0f7-711c-4797-b63f-362f1c313dc3.mov

This should be traced back to the `balanceDisagg` function but am not understanding why it can be so slow to balance the disagg-ed tables in an industry model, while it only takes 1-2 seconds to do so in a commodity model.

@jvendries @bl-young can you take a look into this?

**Comment by jvendries** [comment]
@MoLi7 Yes, this is a pending issue with the disaggregation functions. Namely, disaggregation is not yet tailored to work properly with industry models, and it is possible that some of the disaggregated industry models will not converge. I plan to address this once the summary level disaggregation code is completed.

**Comment by MoLi7** [comment]
The allocation factors for disaggregating IO tables should be the same for Industry and Commodity models, as the IO tables themselves are unchanged for the two types of models.

I figured the problem is caused by disaggregating the wrong `FinalDemand` ([here](https://github.com/USEPA/useeior/blob/master/R/DisaggregateFunctions.R#L491-L497)) then appending it to `FullUse` that can never be balanced.

In an Industry model, we prepare two sets of `FinalDemand`, see [here](https://github.com/USEPA/useeior/blob/master/R/LoadIOTables.R#L126-L134), so `originalFD` should be assigned differently in disaggregation step like so:
```
if(domestic) {
    if (model$specs$CommodityorIndustryType=="Commodity") {
      originalFD <-model$DomesticFinalDemand
    } else {
      originalFD <- model$DomesticFinalDemandbyCommodity
    }
  } else {
    if (model$specs$CommodityorIndustryType=="Industry") {
      originalFD <-model$FinalDemand
    } else {
      originalFD <- model$FinalDemandbyCommodity
    }
  }
```

This applies to `disaggregateInternationalTradeAdjustment` ([link](https://github.com/USEPA/useeior/blob/93f021f5b3ab30a67b1cff93814e8618a4a2cc1f/R/DisaggregateFunctions.R#L160)), too.

I made these changes at my end, and the disaggregation looks successful, see PR #211.

**Comment by MoLi7** [comment]
That's right, I created a new yml file based on USEEIOv2.0-411 and only changed `CommodityorIndustryType` to Industry.

**Comment by jvendries** [comment]
@MoLi7 @bl-young I added a bit of code ([here](https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L22-L24)) to disaggregate the `FinalDemandbyCommodity` and `DomesticFinalDemandbyCommodity `objects which are only present in industry models. With these changes, the `modelbuild()` function runs to completion, generating an industry model that seems correct after visual inspection.  I also tested `modelbuild()` for `USEEIOv2.1-422` to make sure the changes do not alter commodity modify builds (which they didn't). 

However, I did not test the validation functions for the industry model.  Do these functions work with industry models Mo? If so, can you verify that they work correctly?

**Comment by MoLi7** [comment]
Thanks @jvendries ! I added validation on USEEIOv2.0-i-411 in the CI/CD [workflow](https://github.com/USEPA/useeior/runs/5132189093?check_suite_focus=true), but it looks like something is not right. I'm looking into it now.

**Comment by MoLi7** [comment]
For some reason, `model$FinalDemand` in USEEIOv2.0-i-411 is not in industry x final demand form after disaggregation. See below I checked `identical(model$Industries$Code_Loc, rownames(model$FinalDemand))` before and after disaggregation. Could you fix it? @jvendries 

```
> modelname <- "USEEIOv2.0-i-411"
> configpaths <- NULL
> model <- initializeModel(modelname, configpaths)
2022-02-09 14:08:21 INFO::Begin model initialization...
>   # Declare model IO objects
>   logging::loginfo("Initializing IO tables...")
2022-02-09 14:08:27 INFO::Initializing IO tables...
>   if (model$specs$IODataSource=="BEA") {
+     model <- loadNationalIOData(model)
+   } else if (model$specs$IODataSource=="stateior") {
+     # Fork for state model here
+   }
2022-02-09 14:08:27 INFO::Initializing Gross Output tables...
>   # Add Chain Price Index (CPI) to model
>   model$MultiYearIndustryCPI <- loadChainPriceIndexTable(model$specs)[model$Industries$Code, ]
2022-02-09 14:08:29 INFO::Initializing Chain Price Index tables...
>   rownames(model$MultiYearIndustryCPI) <- model$Industries$Code_Loc
>   # Transform industry CPI to commodity CPI
>   model$MultiYearCommodityCPI <- as.data.frame(model$Commodities, row.names = model$Commodities$Code_Loc)[, FALSE]
>   for (year_col in colnames(model$MultiYearIndustryCPI)) {
+     model$MultiYearCommodityCPI[, year_col] <- transformIndustryCPItoCommodityCPIforYear(as.numeric(year_col), model)
+   }
>   # Check for aggregation
>   model <- getAggregationSpecs(model, configpaths)
>   if(length(model$AggregationSpecs)!=0){
+     model <- aggregateModel(model)
+   }
>   # Check for disaggregation
>   model <- getDisaggregationSpecs(model, configpaths)
2022-02-09 14:08:30 INFO::Loading disaggregation specification file for WasteDisaggregationDetail...
> identical(model$Industries$Code_Loc, rownames(model$FinalDemand))
[1] TRUE
>   if(length(model$DisaggregationSpecs)!=0){
+     model <- disaggregateModel(model)
+   }
2022-02-09 14:08:47 INFO::Initializing Disaggregation of IO tables...
> identical(model$Industries$Code_Loc, rownames(model$FinalDemand))
[1] FALSE
```

**Comment by jvendries** [comment]
@MoLi7  looking into it

**Comment by jvendries** [comment]
@MoLi7 I think part of the problem lies in the if-else structure we set up for FD disaggregation for industry models ([here](https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L502-L514), and reproduced below):

 ```
 if(domestic) {
    if (model$specs$CommodityorIndustryType=="Commodity") {
      originalFD <-model$DomesticFinalDemand
    } else {
      originalFD <- model$DomesticFinalDemandbyCommodity
    }
  } else {
    if (model$specs$CommodityorIndustryType=="Commodity") {
      originalFD <-model$FinalDemand
    } else {
      originalFD <- model$FinalDemandbyCommodity
    }
  }
```

When disaggregating industry models the current setup will never enter the 
`originalFD <- model$FinalDemand `

and 
`originalFD <- model$DomesticFinalDemand`

lines. Thus, when the disaggregation function is [called ](https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L17-L19) for these model objects, they are assigned the `model$FinalDemandByCommodity` (and domestic) version of the final demand in the disaggregation. 

I tried adding a new input to the `disaggregateFinalDemand()` function and edited the if-else loops to indicate when to use `model$FinalDemand` when disaggregating industry models. However, this brought us back to the original problem, where the model does not converge during balancing. 

I think the next step, besides changing the above if-else structure, is to modify [`buildDisaggFullUse()`](https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L1358-L1375) to use the `model$FinalDemandbyCommodity ` object instead of `model$FinalDemand` for industry models. 

Mo, does this proposed change make sense from a model build/balance standpoint? 
Is there something else I might be missing with regards to the use of the `model$FinalDemand `object for industry models in other scripts?

**Comment by MoLi7** [comment]
@jvendries thanks for digging into it.
I understand in industry models `model$FinalDemand` is not disaggregated correctly and propose that we touch it at the end of `disaggregateModel` in the same way we [transform](https://github.com/USEPA/useeior/blob/issue_210/R/LoadIOTables.R#L126-L134) the original BEA data. Let me know if the modified function below makes sense.
```
disaggregateModel <- function (model){
 
  logging::loginfo("Initializing Disaggregation of IO tables...")
  
  for (disagg in model$DisaggregationSpecs){
    
    #Disaggregating sector lists 
    model$Commodities <- disaggregateSectorDFs(model, disagg, "Commodity")
    model$Industries <- disaggregateSectorDFs(model, disagg, "Industry")

    #Disaggregating main model components
    model$UseTransactions <- disaggregateUseTable(model, disagg)
    model$MakeTransactions <- disaggregateMakeTable(model, disagg)
    model$UseValueAdded <- disaggregateVA(model, disagg)
    model$DomesticUseTransactions <- disaggregateUseTable(model, disagg, domestic = TRUE)
    
    if(model$specs$CommodityorIndustryType=="Commodity") {
      model$FinalDemand <- disaggregateFinalDemand(model, disagg, domestic = FALSE)
      model$DomesticFinalDemand <- disaggregateFinalDemand(model, disagg, domestic = TRUE)
    } eles {
      model$FinalDemandbyCommodity <- disaggregateFinalDemand(model, disagg, domestic = FALSE)
      model$DomesticFinalDemandbyCommodity <- disaggregateFinalDemand(model, disagg, domestic = TRUE)
    }
    
    #Balancing model
    if(disagg$DisaggregationType == "Userdefined"){
      model <- balanceDisagg(model, disagg)
    }

    #Recalculate model$CommodityOutput and model$IndustryOutput objects 
    model <- calculateIndustryCommodityOutput(model)
    
    #Disaggregating MultiyearIndustryOutput and MultiYearCommodityOutput 
    model$MultiYearCommodityOutput <- disaggregateMultiYearOutput(model, disagg, output_type = "Commodity")
    model$MultiYearIndustryOutput <- disaggregateMultiYearOutput(model, disagg, output_type = "Industry")

    #Disaggregating CPI model objects. Assumption is that the disaggregated sectors have the same CPI values as the original sector. 
    model$MultiYearCommodityCPI <- disaggregateCols(model$MultiYearCommodityCPI, disagg, duplicate = TRUE)
    model$MultiYearIndustryCPI <- disaggregateCols(model$MultiYearIndustryCPI, disagg, duplicate = TRUE)

    #Disaggregating Crosswalk
    model$crosswalk <- disaggregateMasterCrosswalk(model, disagg)
    
    #Disaggregate Margins
    model$Margins <- disaggregateMargins(model, disagg)
    model$InternationalTradeAdjustment <- disaggregateInternationalTradeAdjustment(model, disagg)
    
    # Transform model FinalDemand, DomesticFinalDemand, and InternationalTradeAdjustment to by-industry form
    if (model$specs$CommodityorIndustryType=="Industry") {
      # Keep the orignal FinalDemand (in by-commodity form)
      model$FinalDemand <- transformFinalDemandwithMarketShares(model$FinalDemand, model)
      model$DomesticFinalDemand <- transformFinalDemandwithMarketShares(model$DomesticFinalDemand, model)
      model$InternationalTradeAdjustment <- unlist(transformFinalDemandwithMarketShares(model$InternationalTradeAdjustment, model))
    }
  }
  
  return(model)
  
}
```

**Comment by MoLi7** [comment]
> I think the next step, besides changing the above if-else structure, is to modify [`buildDisaggFullUse()`](https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L1358-L1375) to use the `model$FinalDemandbyCommodity ` object instead of `model$FinalDemand` for industry models.

Yes, we should add `if-else` throughout the disagg script to ask every related function to take the correct `FinalDemand` according to model type, e.g. https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L1327

**Comment by jvendries** [comment]
A question on the following part: 

> # Transform model FinalDemand, DomesticFinalDemand, and InternationalTradeAdjustment to by-industry form
>     if (model$specs$CommodityorIndustryType=="Industry") {
>       # Keep the orignal FinalDemand (in by-commodity form)
>       model$FinalDemand <- transformFinalDemandwithMarketShares(model$FinalDemand, model)
>       model$DomesticFinalDemand <- transformFinalDemandwithMarketShares(model$DomesticFinalDemand, model)
>       model$InternationalTradeAdjustment <- unlist(transformFinalDemandwithMarketShares(model$InternationalTradeAdjustment, model))
>     }
>   }

By this point, the `model$FinalDemand ` object would have been disaggregated and assigned `model$FinalDemandbyCommodity`. Is this the correct input form for the `transformFinalDemandwithMarketShares()` function? In other words, will passing in what is effectively `model$FinalDemandbyCommodity` to the `transformFinalDemandwithMarketShares()` result in an industry by FD `model$FinalDemand` object?

**Comment by MoLi7** [comment]
I also made changes to the 'Disaggregating main model components' step:
```
if(model$specs$CommodityorIndustryType=="Commodity") {
  model$FinalDemand <- disaggregateFinalDemand(model, disagg, domestic = FALSE)
  model$DomesticFinalDemand <- disaggregateFinalDemand(model, disagg, domestic = TRUE)
} eles {
  model$FinalDemandbyCommodity <- disaggregateFinalDemand(model, disagg, domestic = FALSE)
  model$DomesticFinalDemandbyCommodity <- disaggregateFinalDemand(model, disagg, domestic = TRUE)
}
```
Therefore, `model$FinalDemand` will stay unchanged until the transform step you referred to.

And you are right, the transformation should use `model$FinalDemandbyCommodity` instead.
```
# Transform model FinalDemand, DomesticFinalDemand, and InternationalTradeAdjustment to by-industry form
if (model$specs$CommodityorIndustryType=="Industry") {
  # Keep the orignal FinalDemand (in by-commodity form)
  model$FinalDemand <- transformFinalDemandwithMarketShares(model$FinalDemandbyCommodity, model)
  model$DomesticFinalDemand <- transformFinalDemandwithMarketShares(model$DomesticFinalDemandbyCommodity, model)
  model$InternationalTradeAdjustment <- unlist(transformFinalDemandwithMarketShares(model$InternationalTradeAdjustmentbyCommodity, model))
}
```

**Comment by jvendries** [comment]
That makes sense, thanks Mo. Have you pushed these changes or should I copy them over to my local version?

**Comment by MoLi7** [comment]
Just pushed the changes in [781a3f5](https://github.com/USEPA/useeior/pull/211/commits/781a3f5b27600a91a754e4b9c6daf7b2f4ae3ea2). I will let you make sure `buildDisaggFullUse` and similar functions are compatible with industry models.

**Comment by jvendries** [comment]
@MoLi7 A question - I'm running into an error when trying to disaggregate the `model$InternationalTradeAdjustment` object for the industry model. It seems that this object's row names are changed when it is transformed using `transformFinalDemandwithMarketShares() ` ([here ](https://github.com/USEPA/useeior/blob/issue_210/R/LoadIOTables.R#L133)). Before this line, `model$InternationalTradeAdjustment` has industry codes as the row names, but after it, the row names are 

```
V11
V12
V13
...
```

As the row names are needed in the disaggregation function, this results in an error. 

I am not sure where within `transformFinalDemandwithMarketShares() ` the change happens - can you take a look? I will track it down as well but figured since you are more familiar with this part of the code you might have a better idea of where to look.

**Comment by jvendries** [comment]
> I think the loss of row names was caused by an unnecessary `unlist` in the transformation step, so I removed it in [92192aa](https://github.com/USEPA/useeior/pull/211/commits/92192aa7b97192ce67411acfd9a68d59fce381fb). `model$InternationalTradeAdjustment` should retain the correct row names now.

This approach results in `model$InternationalTradeAdjustment`  being a named double for commodity models, but a list for industry models, which presents other problems for disaggregation. Additionally, while I'm not sure if it presents problems elsewhere in the package, the result would be an inconsistent data type between `model$InternationalTradeAdjustment`  and `model$InternationalTradeAdjustmentbyCommodity`, which I think is something we should avoid. 

As an alternative, I propose the following approach: 

```
133 model$InternationalTradeAdjustment <- unlist(transformFinalDemandwithMarketShares(model$InternationalTradeAdjustment, model))
134  names(model$InternationalTradeAdjustment) <- model$Commodities$Code
```

This avoids the issue of the different data types for the similar model objects, avoids the need of additional modifications to the `disaggregateInternationalTradeAdjustments()` function, and allows industry models to run to completion. Does this approach work for you? Do you foresee any problems with it?

**Comment by MoLi7** [comment]
Yes, we should use consistent data type for the two items, and now I recall why the `unlist` was added - it was to force `model$InternationalTradeAdjustment` to be a numeric vector just like `model$InternationalTradeAdjustmentbyCommodity`.

Sorry for the hasty removal of `unlist`, you can revert my last commit and continue with your proposal. I only have one comment: in line 134 it should be `names(model$InternationalTradeAdjustment) <- model$Industries$Code_Loc` because this is for industry models and row/column names of the other IO tables are in the `Code_Loc` form.

In the meantime, we should assign names to the original `model$InternationalTradeAdjustment`, too. Could you replace https://github.com/USEPA/useeior/blob/issue_210/R/LoadIOTables.R#L103-L105 with
```
  # Use model$Commodities
  colnames(model$MakeTransactions) <- rownames(model$UseTransactions) <- rownames(model$DomesticUseTransactions) <- 
    rownames(model$FinalDemand) <- rownames(model$DomesticFinalDemand) <- 
    names(model$InternationalTradeAdjustment) <- model$Commodities$Code_Loc
```

Hope this makes sense.

**Comment by jvendries** [comment]
@MoLi7 I pushed the changes we discussed. I tested these changes with the `"USEEIOv2.0-i-411"` and `"USEEIOv2.0-411"` models and they both run to completion (still waiting on the results of the github validation checks). Would you please take a quick look at the changes to make sure they make sense? In particular, it would be helpful if you could take a quick look at [this ](https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L34-L43) part of the disaggregation functions script to see if there is a better way of accomplishing the if-else functionality required for the Industry and Commodity output calculations. 

Thanks for all your help!

**Comment by MoLi7** [comment]
Thank you for making all the changes.
Re:
> it would be helpful if you could take a quick look at [this ](https://github.com/USEPA/useeior/blob/issue_210/R/DisaggregateFunctions.R#L34-L43) part of the disaggregation functions

I think we can disregard the `if-else`, just use `model <- calculateIndustryCommodityOutput(model)` since the method for calculating output should stay the same for commodity and industry models.

Btw, the workflow run failed after your latest commits due to a missing function doc file. I added it and let's wait on the CMD and validation checks.

**Comment by jvendries** [comment]
I advise against getting rid of that `if-else` block. I tried just using `model <- calculateIndustryCommodityOutput(model)`, and it resulted in a scenario where `model$FinalDemand` was used where it should be `model$FinalDemandbyCommodity` for industry models. However, I could not think of a better alternative to handle that.
