### ISSUE TITLE
Consider shifting to make table for industry and commodity output

### ISSUE THREAD

**Issue by bl-young** [USEPA/useeior#218]
Summarizing a conversation with @MoLi7 , @jvendries 

Current method for calculating output in `useeior` is using use table columns:
https://github.com/USEPA/useeior/blob/d1365d9d98813fb36e7c9d9f46711b846c6308ed/R/LoadIOTables.R#L217-L222

However, for two-region models, the industry output from the make table can diverge from the use table, most likely due to calculations of value add. In `stateior`, the two-region models use make table as the source of output.

When disaggregating a two-region model, `useeior` switches to a use-based calculation which results in error here:
https://github.com/USEPA/useeior/blob/d1365d9d98813fb36e7c9d9f46711b846c6308ed/R/IOFunctions.R#L72-L83

Proposed solution is to switch `useeior` to use a make table based approach for calculating industry and commodity output.

Using the make table will also better support calculating output for hybrid/mixed-unit models.

**Comment by bl-young** [comment]
@MoLi7 found [0.4% and -0.9%] difference in N matrix values for `USEEIOv2.0.1-411` when using make table for industry output.

**Comment by bl-young** [comment]
@WesIngwersen  tagging for your input. Do you recall any reasons why we should not use the make table here?

**Comment by WesIngwersen** [comment]
We debated this thoroughly for state model creation so we need to review the substance of that debate. I can try to find it.

**Comment by MoLi7** [comment]
> We debated this thoroughly for state model creation so we need to review the substance of that debate. I can try to find it.

Any luck on finding the substance of the debate? @WesIngwersen

**Comment by WesIngwersen** [comment]
Related Jira discussions (for those with access)

[Change source of model commodity output](https://epalca.atlassian.net/browse/USEEIO-964)

[Compare industry output in Use to that in Make](https://epalca.atlassian.net/browse/USEEIO-970)

**Comment by WesIngwersen** [comment]
@jvendries @bl-young  We need to discuss your proposed WIO approach separately before making any changes to support it

**Comment by bl-young** [comment]
@MoLi7 , given your plan to adjust stateior to use the use table (https://github.com/USEPA/stateior/issues/12), will we plan to close this issue with no change?

**Comment by MoLi7** [comment]
> @MoLi7 , given your plan to adjust stateior to use the use table ([USEPA/stateior#12](https://github.com/USEPA/stateior/issues/12)), will we plan to close this issue with no change?

Yes please. Thanks for the discussion!
