### ISSUE TITLE
demand vector referencing - inconsistency in docs and accepted values

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#220]
The example here show passing the full name of the demand vector, like `CompleteProduction`
https://github.com/USEPA/useeior/blob/215ebcb50a1f68df3e30230fe82bb0f4c6bb23fb/README.md?plain=1#L71

Also the names are given here
https://github.com/USEPA/useeior/blob/master/format_specs/ModelSpecification.md#demand-vector-specifications

but this actually fails, the function is expecting just "Production" and then will tack on "Complete" or "Domestic"

**Comment by MoLi7** [comment]
Right, the example in README and demand vector specs need to be updated. Hot-fix in `master` or maintenance fix in `develop`?

**Comment by MoLi7** [comment]
I corrected the example in README, now `calculateEEIOModel` is passed correct param values.

As for the demand vector specs, they are actually consistent with [those in the `yml` file](https://github.com/USEPA/useeior/blob/develop/inst/extdata/demandspecs/DefaultDemandVectors.yml). No change is needed here.
