### ISSUE TITLE
CI testing check failing

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#222]
The checks automated in github actions are still failing for master

**Comment by WesIngwersen** [comment]
can we do a hotfix to address these?

**Comment by MoLi7** [comment]
The failing is NOT on `master`, see https://github.com/USEPA/useeior/actions?query=branch%3Amaster.

Currently in README, the CMD check badge refers to the most recent actions result - failing on `updateIO` branch. According to [this GitHub doc](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter), there is a way to point to a branch, but I found it doesn't work as it says, [so did someone else](https://github.com/github/docs/discussions/3168).

Given the situation, there are two hotfix options:

1. **Correct the source error**, which should be having `stateior` as dependency in DESCRIPTION. This is true for branches including `updateIO`, `linkstateior`, `develop`, so removing it will interfere with integration of state IO.
2. **Manually run the CMD check on `master` overwrite the failing status**, but this is only a temporary fix - itself will be overwritten whenever the same check is triggered by push/pull request in the feature branches.

**Comment by MoLi7** [comment]
I manually re-run the CMD check workflow, now the status badge shows 'passing'. Hotfix option 2 works, but still has the limitation of being easily overwritten.

Rethinking about option 1. The reason for failing on `updateIO` is [labeled as 'error in syntax'](https://github.com/USEPA/useeior/actions/runs/2110899686/workflow) which is odd. Looking into it now.

**Comment by MoLi7** [comment]
Update on the syntax error on `updateIO`: the indentation in `R-CMD-check.yaml` was messed up, took me three commits (45a79345f496015fda7843ed9098cc477efbd627 and 2 precedents) to fix them all.

Pushing commit to `updateIO` is set to not trigger any actions workflow, and that is what I'm seeing now - 45a79345f496015fda7843ed9098cc477efbd627 did not trigger any workflow run.

To update status badge in `master`, I'm manually re-running the check now.
