### ISSUE TITLE
useeior and stateior cannot (?) depend on each other

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#225]
When we initialized the integration of state IO data, it was natural to add `stateior` as a dependency of `useeior`. This led to a situation where the two packages are interdependent on each other, as `stateior` needs to use the US IO data in `useeior`.

I didn't read any "don't do it (i.e. the interdependency)" in related documents or discussions, but the `R-CMD-check` failures caused by "[Dependency package 'stateior' not available.](https://github.com/USEPA/useeior/runs/6016529204?check_suite_focus=true#step:12:28)" look very confusing to me, even if I'm pretty sure `statetior` is correctly claimed in `useeior` DESCRIPTION, and vice versa.

Recently, I've been suspecting the failures must be caused by the fact that `stateior` doesn't have a non-beta release yet (i.e. it's not stable), but I'm deep down not convinced that it is the root cause. This makes me re-think about the legitimacy of package interdependency. After some Googling, I ran into a StackOverflow discussion I read before about how possible it is to have interdependent packages and saw [this latest comment saying "it's not possible anymore" ](https://stackoverflow.com/questions/9153847/can-two-r-packages-be-on-each-others-depends-list#:~:text=0-,Updated%20in%202021,-%3A%20this%20is%20not). I don't know if it's true, but I think the R check failures we collected are suggesting maybe package interdependency is fragile.

Therefore, I hope to raise a discussion about the necessity of keeping `stateior` as a dependency of `useeior`.

**Comment by MoLi7** [comment]
Fortunately, `useeior` does not use any `stateior` core functions - all it needs is the functions that load state IO data from Data Commons. These functions now are in `stateior`, but they can be easily migrated to `useeior`, then `stateior` will perform just like `flowsa` - it generates data for `useeior` but is not directly connected with `useeior`.

By creating a few data loading functions in `StateiorFunctions.R`, the same data loading process will be maintained and the installation of a fairly big package `stateior` will be avoided for users. This setup will also eliminate the interdependency and hopefully stop causing `R-CMD-check` failures due to `stateior`.

**Comment by MoLi7** [comment]
@WesIngwersen what do you think?

**Comment by WesIngwersen** [comment]
> @WesIngwersen what do you think?

Yes loading data from the  Data Commons can be done in useeior no matter what package the data are produced by. So i dont know if its better to reproduce the functions from stateior or to make the existing functions to read Data Comms data more flexible. I would think the latter. In any case no we dont need that dependency in useeior

**Comment by MoLi7** [comment]
> So i dont know if its better to reproduce the functions from stateior or to make the existing functions to read Data Comms data more flexible. I would think the latter.

I think we would want to have designated functions for loading different datasets from Data Commons, because State IO and flowsa FBS data (and unknown future data) would require different processing steps. We already have [FlowsaFunctions.R](https://github.com/USEPA/useeior/blob/master/R/FlowsaFunctions.R), I hope to create **StateiorFunctions.R** for state IO data exclusively.
