### ISSUE TITLE
Error in col assignment in formatIOTableforIOMB

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#23]
The col headers are incorrect for the used and other commodities when formatted for iomb 
https://github.com/USEPA/useeior/blob/4019fff557f8154bf3ecee591152e6c923f6e3cd/R/WriteModel.R#L27

Demonstrated in
modelname <- "USEEIOv2.0.16s-GHG"
found: 
last two column names are 
l <- ncol(DirectRequirementsCoefficients)
> colnames(DirectRequirementsCoefficients[,c(l-1,l)])
[1] "used/farms/us"                                     
[2] "other/forestry, fishing, and related activities/us"

somehow its grabbing the names for the first two commodities

**Comment by MoLi7** [comment]
[This commit](https://github.com/USEPA/useeior/commit/2313c3a40c750bc8943d66fe65c2bc2fbe425bc8) should fix this issue.
