### ISSUE TITLE
Review annual BEA release

### ISSUE THREAD

**Issue by bl-young** [USEPA/useeior#240]
Review available BEA data updates

https://www.bea.gov/news/schedule

**Comment by bl-young** [comment]
as a side note, [the action that was created](https://github.com/USEPA/useeior/actions/runs/3056954196) to generate this issue automatically failed. I believe because it uses a third party repo for the scheduling
> jasonetco/create-an-issue@v2.6.0 is not allowed to be used in USEPA/useeior. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: cloud-gov/*, softprops/turnstyle@v1, zaproxy/*, r-lib/actions/*, docker/*.

Similar to the [issue in lciafmt](https://github.com/USEPA/LCIAformatter/issues/85)

**Comment by MoLi7** [comment]
Thanks Ben. Restriction on third party Actions supposedly can be lifted in Settings (see [instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-specific-actions-to-run)) but could cause security concerns.

**Comment by MoLi7** [comment]
Hey @WesIngwersen and @bl-young , looks like BEA has updated some underlying tables (GDP, CPI, etc.) to include 2021 data. If you consider pulling them in, running the [save-BEA-data Actions workflow](https://github.com/USEPA/useeior/actions/workflows/save-BEA-data.yaml) should download and save those new tables automatically.

**Comment by bl-young** [comment]
updated with #249
