### ISSUE TITLE
Special session IIOA conference

### ISSUE THREAD

**Issue by konstantinstadler** [USEPA/useeior#245]
Hi folks,

Just a short question:
I check if there is enough interest for a special session on Open Source software for IO development/analysis at the IIOA 2023 (https://iioa.org/conferences/29th/important_dates.html ). Would any of the authors of IO-Model-Builder to be interested in presenting there?

Cheers
Konstantin

**Comment by WesIngwersen** [comment]
Hi @konstantinstadler The IO-Model-Builder is no longer used for building USEEIO models but I assume you understand that since posting the question in this repo. Thank you for this note, but please contact me by email with this type of question.
