### ISSUE TITLE
Add more docs for model types supported and use

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#265]
We've added new types of models supporting  (at least supported in WIO branch) and they are now on [model specifications docs](https://github.com/USEPA/useeior/blob/WIO/format_specs/ModelSpecification.md) under model type, but there is no guidance on how to create and use them. New fields like "WIOspecs" also need to be described in these docs.  The types of additional files required needs to be described for new models.

**Comment by bl-young** [comment]
Can point to the HIO repo for examples
