### ISSUE TITLE
USEEIO Version Online

### ISSUE THREAD

**Issue by emehlhop** [USEPA/useeior#279]
Hello,

Just trying to make sure we have the most up to date version of this dataset. The version published here https://catalog.data.gov/dataset/useeio-v2-0-1-411 says that is was run on useeior v1.0.0

Would we need to run the code using useeior v1.1.1 to get the most current version? Thank you!

**Comment by bl-young** [comment]
We always recommend using the latest version of the package. Note that specific model specs (and the data they use) are not necessarily tied to the version of the r package itself. The package may get updated with new features or bug fixes while the underlying model remains unchanged.
