### ISSUE TITLE
Adjust scrap prior to deriving A matrix

### ISSUE THREAD

**Issue by cga203** [USEPA/useeior#28]
In useeior its missing to adjust scrap in market shares matrix before multiplying the normalized use and normalized make table to obtain the A matrix. In specific, in function generateMarketSharesfromMake().

**Comment by WesIngwersen** [comment]
@cga203 Correct this has not yet been implemented.

**Comment by WesIngwersen** [comment]
In the near future we have not intention of removing the scrap commodity as it creates other balancing challenges.
