### ISSUE TITLE
2R models: Consider removing export residual from consumption vector

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#298]
https://github.com/USEPA/useeior/blob/ae9d9694479d680084556323471eadfdb1def968/R/StateiorFunctions.R#L179-L195

The export residual is defined in Li et al 2022 as:

_The exceptions are the industries in which all consumption was assumed to be local. In this case, since no interregional trade is assumed, the distribution of a discrepancy between supply and demand affecting other regions would necessarily result in a model with negative interregional imports, which is untenable from the economic point of view. In this case, the difference between supply and
demand is included as a new component of final demand that is called the “export residual”. For commodities that have SoI2SoI ICF ratio equal to 1, their “export residual” equals their “interregional exports”._

This is a balancing term because it these are commodities not consumed locally and it creates an imbalance if they are assigned to RoUS consumption (and these are interregional and not international exports).

**Comment by WesIngwersen** [comment]
My recommendation would be to remove it from the consumption vector

**Comment by WesIngwersen** [comment]
https://github.com/USEPA/useeior/issues/298

**Comment by jvendries** [comment]
@WesIngwersen I [removed ](https://github.com/USEPA/useeior/commit/d1886338c7b007c0b57177b5fc2dbe4646696d37) the export residual from the consumption vector, and created [model](https://github.com/USEPA/useeior/blob/issue_298/tests/2019_GA_NO_ExpRes.rds) [objects ](https://github.com/USEPA/useeior/blob/issue_298/tests/2019_GA_with_ExpRes.rds) and a [script ](https://github.com/USEPA/useeior/blob/issue_298/tests/Issue_298_299.rmd) to check that this change did not have any major impacts. Nothing changes besides objects dependent on the final consumption vector itself (`CbS` and `B_h`), and the household final demand resulting from models with and without the export residual are equivalent, suggesting this change is OK. This should be fine to pull into develop.

**Comment by WesIngwersen** [comment]
@jvendries please create PR to pull into develop, thanks

**Comment by jvendries** [comment]
> @jvendries please create PR to pull into develop, thanks

@WesIngwersen @bl-young I created a pull [request ](https://github.com/USEPA/useeior/pull/300) for this issue. I also moved and  tested the rmd script and model objects related to this issue to [useeio_team ](https://github.com/USEPA/USEEIO_team/commit/3b1fde14220bbe0bcc6c4415576603e6d18ad9f5) to avoid pulling those into develop.
