### ISSUE TITLE
Adjust some post-model build analytical functions for models with ImportFactors as they lack M and N

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#305]
For new models using external import factors like `USEEIOv2.3-s-GHG-19` 
some public functions will fail like
`calculateSectorPurchasedbySectorSourcedImpact()`
`disaggregateTotalToDirectAndTier1()`

as `M` and `N` are not present but rather just `M_d`, `M_m`, `N_d`, `N_m`

**Comment by bl-young** [comment]
Yes we will either need an approach to derive an aggregate `M` and `N` or we need to put a warning/stop on those functions for now.

**Comment by WesIngwersen** [comment]
done with [a8db500](https://github.com/USEPA/useeior/commit/a8db500d6ddee84d010bf0226962223886cf41ad).
