### ISSUE TITLE
Consider not exporting print2RValidationResults and validate2RCommodityTotals

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#307]
refers to https://github.com/USEPA/useeior/blob/efaed73f7726d0c59903d9bc7e4948acd757a91b/R/StateiorFunctions.R#L207 and https://github.com/USEPA/useeior/blob/efaed73f7726d0c59903d9bc7e4948acd757a91b/R/StateiorFunctions.R#L262

2R model calculation and results functions are treated equally to 1R models in build and calculate and other fxns for external users; why not incorporate print2RValidationResults()  into https://github.com/USEPA/useeior/blob/efaed73f7726d0c59903d9bc7e4948acd757a91b/R/ValidateModel.R#L299 so its treated equally for validation as well? It can call `print2RValidationResults()` if needed, but might be too duplicative and better just to edit `printValidationResults()` to handle it  

And then why does  `validate2RCommodityTotals()` stand alone? Why not make it internal and incorporate it into `printValidationResults()` when the model is 2R?

**Comment by bl-young** [comment]
> It can call `print2RValidationResults()` if needed, but might be too duplicative and better just to edit `printValidationResults()` to handle it

Yes, `print2RValidationResults()` did get pulled into the main `printValidationResults` [here](https://github.com/USEPA/useeior/blob/f938989e9663a94cdd5c244ada8d5e2de00e0e18/R/ValidateModel.R#L340-L342) for the reason you describe. So it does not need to be called separately.

@jvendries can you confirm, is validate2RCommodityTotals only used internally (i.e., in useeio_team?)
