### ISSUE TITLE
Improve or drop aggregateResultMatrix

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#309]
https://github.com/USEPA/useeior/blob/636a81b3f6a806a6c3b1d50f62c0cc4de977b9fe/R/CalculationFunctions.R#L417

correct usage would be for example, with `model` being a model object  already built and assume model is a summary level model (would also work for detail)
```
A_d_sector <- aggregateResultMatrix(model$A_d, "Sector", model$crosswalk)
```

But this is not well documented, no examples are given and inconsistent with other functions like `adjustResultMatrixPrice()` where one specifies  the matrix like `A_d` and not having to pass `model$A_d`.  and also having to pass the whole `model$crosswalk` is odd  and then not clear what matrices can be passed... docs say "result matrix" but this actually fails for what are called result matrices like `M` and `N` that are not sector x sector.

**Comment by bl-young** [comment]
I've clarified the descriptions for this and `aggregateResultMatrixbyRow()` in a61fc47. One is designed to aggregate a result matrix (`G` or `H`) while the other is to aggregate a sector by sector result such as what comes out of [calculateSectorPurchasedbySectorSourcedImpact()](https://github.com/USEPA/useeior/blob/6d5209aa756f793ef850500bb39009b2c952cdb2/R/CalculationFunctions.R#L269-L284)
