### ISSUE TITLE
Consider a grouping variable in model object for matrices

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#35]
Matrices have to been manually named to write out to API , useeiopy, or just as csv.

**Comment by WesIngwersen** [comment]
like model$matrices$A

**Comment by MoLi7** [comment]
Moving matrices like A to model$matrices, or adding model$matrices$A in addition to model$A?

**Comment by WesIngwersen** [comment]
It would be moving objects, not duplicating them.

**Comment by MoLi7** [comment]
Ok, I will work on it in a new branch.

**Comment by WesIngwersen** [comment]
@MoLi7 before you invest too much time on this, let's work discuss it in our meeting today

**Comment by WesIngwersen** [comment]
Decided against grouping and instead we removed some additional unneeded matrices
