### ISSUE TITLE
Change $ year in final demand

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#4]
like @ #3 
Change needs to be made about here
https://github.com/USEPA/useeior/blob/master/R/DemandFunctions.R#L19

No adjustment should need to be made because Final Demand are already in IOYear because they come from the IO Use

**Comment by WesIngwersen** [comment]
FYI @AndreAvelino

**Comment by MoLi7** [comment]
@WesIngwersen Per Andre's comment, I think we should use DomesticFinalDemand, instead of FinalDemand, to derive USTotalConsProd.

**Comment by WesIngwersen** [comment]
FinalDemand still has the rfeferencecurrencyyear adjustment
https://github.com/USEPA/useeior/blob/master/R/BuildModel.R#L49
