### ISSUE TITLE
lineplotcoefficients error - reference var not defined in scope

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#48]
https://github.com/USEPA/useeior/blob/a56129051db01a45bf4303dd1275bfd4b8738e6e/R/VisualizationFunctions.R#L47

df_model is not defined with this functions scope

**Comment by MoLi7** [comment]
@WesIngwersen df_model is created in the for loop above https://github.com/USEPA/useeior/blob/a56129051db01a45bf4303dd1275bfd4b8738e6e/R/VisualizationFunctions.R#L33, it should be available for passing to ggplot2::theme. I tested it [here](https://github.com/USEPA/useeior/blob/a56129051db01a45bf4303dd1275bfd4b8738e6e/examples/WaterModelGraphs.R#L20) and it worked for me.

**Comment by WesIngwersen** [comment]
It's actual here is the var definition problem. sorry i was wrong before
https://github.com/USEPA/useeior/blob/a56129051db01a45bf4303dd1275bfd4b8738e6e/R/VisualizationFunctions.R#L32

model isn't defined.. in your example you happen to have used the same variable and that's why it worked.

**Comment by WesIngwersen** [comment]
@MoLi7  This will trigger it
https://github.com/catherinebirney/water_use_methods/blob/41fb5e68b5672c5b780a9edf27c08c3334dd5e21/Results.Rmd#L26
