### ISSUE TITLE
GrossOutput 6 orders of mag to high in models

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#50]

**Comment by WesIngwersen** [comment]
fixed

**Comment by MoLi7** [comment]
Fixed by this [commit](https://github.com/USEPA/useeior/commit/c1ad7f2a76e6bb096bc79b1bdb02e34c7ff2a95e).

I re-generated USEEIOv2.0.10-GHG model and validated its coefficients match the ones in the Supply Chain GHG report, so I think we can confirm this issue is fixed by the commit above.
