### ISSUE TITLE
Make calculation flexible for different demands and domestic requirements

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#7]

**Comment by MoLi7** [comment]
@WesIngwersen Could you explain a bit more about how you vision **A**, **Demand**, **f** (https://github.com/USEPA/useeior/blob/7244151dda5db681f2d01c8bdf006660ccd2d67e/R/CalculationFunctions.R#L12-L24) being used in calculateEEIOModel() and/or writeModelComponents()?
I suppose **f** will replace **model$f** in https://github.com/USEPA/useeior/blob/7244151dda5db681f2d01c8bdf006660ccd2d67e/R/CalculationFunctions.R#L44?

**Comment by WesIngwersen** [comment]
They are just temporary variables for use within that functions' scope. It simply an assignment of the appropriate A and Demand from the model object to perform the calculations. No need to assign model variables for them.
