### ISSUE TITLE
Error with writeModelforApi

### ISSUE THREAD

**Issue by TheTisiboth** [USEPA/useeior#78]
I'm getting an error when I try to use this function. Maybe I am doing something wrong ? But it is the script `USEEIO20-GHG.R` from the branch `master`.

```
library(useeior)

# See the versioning scheme for explanation of model names (https://github.com/USEPA/USEEIO/blob/master/VersioningScheme.md)
useeior::seeAvailableModels()
model <- useeior::loadIOData('USEEIOv2.0-GHG')
model <- useeior::loadandbuildSatelliteTables(model)
model <- useeior::loadandbuildIndicators(model)
model <- useeior::buildEEIOModel(model)
result <- useeior::calculateEEIOModel(model, perspective='DIRECT')

modeloutdir="C:\\Users\\Nutzer\\Documents\\git\\useeior\\examples"
# Write model for API
useeior::writeModelforAPI(model,modeloutdir)
```

Gives me the following error : 

```
> useeior::writeModelforAPI(model,modeloutdir)
2021-01-20 15:25:13 INFO::Model matrices for API written to C:\Users\Nutzer\Documents\git\useeior\examples/build/data/USEEIOv2.0-GHG.
Fehler in fix.by(by.x, x) : 'by' must specify a uniquely valid column
Zusätzlich: Warnmeldungen:
1: In if (!is.na(model)) { :
  Bedingung hat Länge > 1 und nur das erste Element wird benutzt
2: In if (is.na(model)) { :
  Bedingung hat Länge > 1 und nur das erste Element wird benutzt
```

**Comment by WesIngwersen** [comment]
I'm actively revising this at the moment in the refac_indicators branch. You can [contact me](https://github.com/WesIngwersen) directly if you want more information. thanks

**Comment by TheTisiboth** [comment]
Oh great! Thank you for the quick answer, I'm gonna have a look at it.

**Comment by WesIngwersen** [comment]
This should be working now for that model in v2-alpha

**Comment by TheTisiboth** [comment]
Hello Winsley
Thank you for keeping me up to date!

Sadly, I am getting an error as I try to run the following line :
`model <- useeior::loadandbuildIndicators(model)`

The error is the following :

`ModuleNotFoundError: No module named 'lciafmt'`

However, I have successfully installed it (I can import lciamft in a
Python script with success).

Do you know such an issue ?

I keep looking why I get this error.

Thank you again

Léo
