### ISSUE TITLE
Separate out currency year adjustment and price type conversion from calculation result

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#8]

**Comment by WesIngwersen** [comment]
I propose the new external function adjustMultiplierPrice(currency_year (int), purchaser_price=TRUE, margin_type="industry") that will provide price adjusted U and M matrices. These U and M could be labelled like U_pur_ind_2018  for purchaser prices using industry margins in 2018 dollars inside a new list object (rather than making it part of model or result).

**Comment by WesIngwersen** [comment]
I would also propose removing ReferenceCurrencyYear from the model config files. I would suggest a using a file input-output methods to open the .yml files and find (using grep) and remove that line from those files

**Comment by MoLi7** [comment]
In adjustMultiplierPrice function, should **adjusting price to currency_year** always be implemented in the very last step?

**Comment by MoLi7** [comment]
Removing ReferenceCurrencyYear from model config essentially means eliminating getAdjustedOutput function as well as its presences in other functions.

**Comment by WesIngwersen** [comment]
> In adjustMultiplierPrice function, should **adjusting price to currency_year** always be implemented in the very last step?

Yes, in the last step.

**Comment by WesIngwersen** [comment]
@MoLi7  Lets just update the per dollar impact matrices per now, so write a generic function that will work for either D, M, or U  matrices.  We do not need to modify the calculateEEIOModel function

**Comment by WesIngwersen** [comment]
> Removing ReferenceCurrencyYear from model config essentially means eliminating getAdjustedOutput function as well as its presences in other functions.

The satellite tables still need getAdjustedOutput
https://github.com/USEPA/useeior/blob/master/R/SatelliteFunctions.R#L54

**Comment by MoLi7** [comment]
> @MoLi7 Lets just update the per dollar impact matrices per now, so write a generic function that will work for either D, M, or U matrices. We do not need to modify the calculateEEIOModel function

I completed the adjustMultiplierPrice function [here](https://github.com/USEPA/useeior/commit/2b81fdc531855270990d170a18d60aa247edd68a), which needs further edits to ensure the IO_year_to_currency_year multiplication is done correctly.

**Comment by WesIngwersen** [comment]
@MoLi7 Thanks, this is the idea. I think it would be better to declare the matrices to apply this too and not adjust all - so just B, D, M, and U for now.  Like the producer price adjustment, we could perform the currency year adjustment as a matrix multiplication of a diagonalized currency adjustment factors as opposed to using sweep.. just make sure alignment of the dimensions for that is correct. Add to the result some character variables that indicate the price type and currency year of the results so these can be identified by just looking at the result list.

**Comment by WesIngwersen** [comment]
Please test this with some known data. Ideally we should be building unit tests with a small independently calculated IO model to test these functions

**Comment by MoLi7** [comment]
> Please test this with some known data. Ideally we should be building unit tests with a small independently calculated IO model to test these functions

Currently, B and M derived using adjustMultiplierPrice(currency_year=2017, purchaser_price=TRUE, margin_type="final consumer", model1) are quite different from those serving as results of GHG report. I suspect it is caused by unnecessary price adjustment in buildEEIOModel and related functions, I will look into it.

**Comment by MoLi7** [comment]
@WesIngwersen Although getAdjustedOutput may be needed for satellite tables, it should not be used here (https://github.com/USEPA/useeior/blob/b9b6c7c39100afd9514905dbe1c8f9c9a2d6e236/R/IOFunctions.R#L105), since we want to move all currency_year price adjustment to adjustMultiplierPrice. Furthermore, we need to think over whether to apply currency_year price adjustment in satellite tables.

**Comment by MoLi7** [comment]
@WesIngwersen Please review updated adjustMultiplierPrice [here](https://github.com/USEPA/useeior/commit/6cf9988a808589bbee0476be6632aa0b8936d555).

**Comment by WesIngwersen** [comment]
Per discussion we will make this function work for passed matrices, and not a fixed list

**Comment by MoLi7** [comment]
Solved by adjustMultiplierPrice function in [CalculationFunctions.R](https://github.com/USEPA/useeior/blob/master/R/CalculationFunctions.R)
