### ISSUE TITLE
Row order for flows and indicators csv written for API doesn't match order in matrices

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/useeior#83]
The index for the these metadata files must match the order in the matrices where they appear as rows or columns

**Comment by WesIngwersen** [comment]
@MoLi7 let me know if you can look into this

**Comment by MoLi7** [comment]
Sure I will take a look now.

**Comment by MoLi7** [comment]
This [commit](https://github.com/USEPA/useeior/commit/9e0471bb61c3b5650123558e5ebcd3ee5749c7af) should fix the issue, I was working in disaggregation branch so it's there. If you want it in another branch, please cherry-pick it.

Note that [`sectors$ID`](https://github.com/USEPA/useeior/blob/7aa015c0a718a3d4a123eee8f35fb94ab300f948/R/WriteModel.R#L222) includes `Name` which is slightly different from the column names of `model$B` and `model$U`, but I've checked that their order are the same.

**Comment by WesIngwersen** [comment]
I had incorrectly stated "sectors" instead of "flows" in the title.  I will work on the flows ordering

**Comment by WesIngwersen** [comment]
The $Index, which is what is used to align the names in this metadata with the model matrices in the SMM Tools, always has to be created following the completion of all ordering operations. This is corrected now.

**Comment by WesIngwersen** [comment]
The flows in SatelliteTables$flows and in the B matrix are not the same.. 2641 for USEEIO2.0 in B verses 2671 in $flows so this still needs to be addressed

**Comment by bl-young** [comment]
These flows that appear in $flows but not B are flows that don't have any assigned sectors in totals_by_sector, I'm looking into see why that happens

**Comment by bl-young** [comment]
In one case, the only NAICS (or I assume a single facility) that reports cumene hydroperoxide to water lists NAICS 325192, which is a NAICS that expired after 2007.

There are records in CRHW from RCRA/stewi that are coming in at 5 digit NAICS, but they are listed as having a "." at the end, so "11115." Trying to identify where this is happening.

**Comment by WesIngwersen** [comment]
Thanks @bl-young. Did you recheck the flows in each table after that?

**Comment by bl-young** [comment]
A difference of 5 flows remains, all 5 (3 CRHW, 1, GRDREL, 1 WATREL) are due to only appearing listed for NAICS that don't exist for 2012 but either use 2007 or 2017 NAICS codes.

**Comment by WesIngwersen** [comment]
I think this is a flowsa issue so I added that referenced issue.

**Comment by bl-young** [comment]
This commit now checks for this missing flow issue specifically https://github.com/USEPA/useeior/commit/33d35d15f8e13b584637f4e1b385005fc1cece88
