### ISSUE TITLE
Disaggregated model$MakeTransactions (incorrectly) integrated with model$BEA$IndustryOutput

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#86]
I think we have a few underlying IO functions NOT updated after the disaggregation of Make and Use, e.g. [here](https://github.com/USEPA/useeior/blob/9a7d1216a6db543f6bca11daeb6c27568ae218fd/R/IOFunctions.R#L79). This might have messed up the economic calculations to a certain extent.

I discovered it by running the following code:
```
model <- loadIOData('USEEIOv2.0')
C <- normalizeIOTransactions(t(model$MakeTransactions), model$BEA$MakeIndustryOutput) # C = V' %*% solve(x_hat)
# Validation: check if column sums equal to 1
industryoutputfractions <- colSums(C)
for (s in industryoutputfractions) {
  if (abs(1-s)>0.01) {
    print("Error in commoditymix")
  }
}
```
Apparently, several disaggregated waste sectors have `industryoutputfractions` << 1 due to `nrow(model$MakeTransactions) != length(model$BEA$MakeIndustryOutput)`. Although the error reminder pops up here, it definitely does not go off during the process of loading IO data.

Please take a look and let us coordinate on fixing this, thanks!
@WesIngwersen @bl-young @jvendries

**Comment by MoLi7** [comment]
I may have exaggerated the issue in my previous comment 😥, my apologies!

After more thoughts, I realized the economic calculations should not go wrong as long as the disaggregation of waste sectors is correctly implemented - I'm sure @bl-young and @jvendries have done it right.

However, the errors in disaggregated CommodityMix matrix still trouble me: does it make sense that `colSums(C)` of the disaggregated sectors << 1?
@WesIngwersen

**Comment by WesIngwersen** [comment]
@jvendries @bl-young  Could you take a look at this?

**Comment by WesIngwersen** [comment]
Resolved by @jvendries with this commit https://github.com/USEPA/useeior/commit/73f9238802ff634806f4e8b8528ee37257f098ed
