### ISSUE TITLE
Local directory incompatibility between Mac OS and Windows OS

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeior#99]
The current [local directory setup](https://github.com/USEPA/useeior/blob/b31e377db8c05d2d5f995e682f891c57968aeb60/R/UtilityFunctions.R#L120-L161) for downloading and loading parquet files does not work in Mac OS, I believe it is a common issue caused by `/` and `\` between Mac/Linux and Windows OS.

Does anyone know any trick to address such issue?
@WesIngwersen @catherinebirney @bl-young @jvendries

**Comment by WesIngwersen** [comment]
/ works for both and should be used in place of \

**Comment by MoLi7** [comment]
> / works for both and should be used in place of \

Alright, I will replace \ with / and ask you (or other Windows users) to confirm it, thanks!

**Comment by WesIngwersen** [comment]
I have used that convention in many cases in both Python and R but yes i will check the change, thanks!

**Comment by MoLi7** [comment]
@WesIngwersen please pull refac_IO to confirm :)

**Comment by bl-young** [comment]
@MoLi7  data download still worked for me with your new commit. I think we can close this. thanks
